# Generated by Django 5.2 on 2025-04-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
    ]
